# Generated by Django 3.0.4 on 2020-03-15 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='join_date',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, null=True),
        ),
    ]
